README.md
index.js
lib/get-installation-access-token.js
test/test.js

The option can be used to override hardcoded defaults from @octokit/endpoint.
So that we can now use it to work on GitHub Enterprise installations:
```js
const app = new App({
id: APP_ID,
privateKey: PRIVATE_KEY,
baseUrl: 'https://github-enterprise.com/api/v3'
})
```
Closes #13.
-----
[View rendered README.md](https://github.com/anton-rudeshko/app.js/blob/master/README.md)

Add `baseUrl` App option

---

index.d.ts

Looking at the source code looks like the variable should be `installationId` for `getInstallationAccessTokenOptions` not `installation_id`

Fixed *.d.ts variable name to match source code

---

README.md

The example for fetching the installation id uses a variable `body` that doesn't actually exist.
-----
[View rendered README.md](https://github.com/jbjonesjr/app.js/blob/master/README.md)

no body object in example

---

.travis.yml
index.d.ts
package-lock.json
package.json

I'm getting an error with TypeScript due to an @octokit/app.js dependency:
```sh
node_modules/@octokit/app/index.d.ts:7:15 - error TS2694: Namespace 'LRUCache' has no exported member 'Cache'.
7   cache?: LRU.Cache<string, string>
```
This fix solved it. Please have a look.

Fix LRU.cache missing type in TypeScript

---

README.md

ping @chrishiestand does that change make it clear?
-----
[View rendered README.md](https://github.com/octokit/app.js/blob/37/caching-per-instance/README.md)

docs(README): caching per instance

---

src/get-installation-access-token.ts
src/types.ts
test/index.test.ts

Add two new options, `repositoryIds` and `permissions`, as allowed by the
API.
https://developer.github.com/v3/apps/#example

feat: Add all API options to `getInstallationAccessToken`

---

src/get-signed-json-web-token.ts

I initially stumbled upon this comment while reviewing a draft blog post for @JasonEtco but I was instantly confused because "leeway" implies adding something for more freedom.  I had to dig back to find the [issue](https://github.com/probot/probot/issues/942) and [PR](https://github.com/octokit/app.js/pull/36) that brought this code about to understand why the subtraction was indeed the intended action.
This subtraction is more of a preventative safety net, or a "30 second safeguard/buffer", to avoid potentially running into the unpleasantness of...
> ...the maximum expiration time of 10 minutes, after which the API will start returning a 401 error. [\[1\]](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app)

Change comment to more accurately reflect intent

---

src/each-repository.ts
src/types.ts
test/each-repository.test.ts

With this patch, users can optionally pass an installation ID to app.eachRepository to iterate through repositories of one specific installation, as written in README:
```js
for await (const { octokit, repository } of app.eachRepository.iterator({ installationId })) { /* ... */ }
await app.eachRepository({ installationId }, ({ octokit, repository }) => /* ... */)
```
This fixes #188.

Add implementation of eachRepository({ installationId }, callback) (fix #188)

---

README.md

The `response` variable does not exist. The actual response from the API call is destructured and `data` is extracted.
-----
[View rendered README.md](https://github.com/jstastny/app.js/blob/patch-1/README.md)

Fix typo in readme code example

---

package-lock.json
src/webhooks.ts

fix(types): add explicit return type to webhooks() function

---

src/webhooks.ts

follow up to https://github.com/octokit/app.js/pull/201#issuecomment-780700920

docs: add reference to reasoning behind the explicit return type

---

README.md
src/index.ts
src/types.ts
test/oauth.test.ts

also removes mentions of OAuth `scopes` as they are not supported by GitHub Apps
-----
[View rendered README.md](https://github.com/octokit/app.js/blob/remove-scopes/README.md)

feat(typescript): `options.oauth.allowSignup` is optional and boolean

---

README.md
package.json
src/index.ts
test/deprecations.test.ts
test/smoke.test.ts

fixes #205
-----
[View rendered README.md](https://github.com/octokit/app.js/blob/205/createNodeMiddleware/README.md)

feat: `createNodeMiddleware()`. Deprecates `getNodeMiddleware()`

---

package-lock.json
package.json
test/readme-examples.test.ts

See https://github.com/octokit/webhooks.js/pull/518
- default `sign` algorithm for `webhooks.sign` is now `sha256`. Use `webhooks.sign({ algorithm: "sha1", secret }, payload)` to fall back to `sha1`.
- static `sign` and `verify` methods are no longer exported. Use `@octokit/webhooks-methods` package instead
- `webhooks.sign()` and `webhooks.verify()` are now asynchronous

fix(deps): bump `@octokit/webhooks` to `9.0.0-beta.5`

---

package-lock.json
package.json
src/middleware/node/index.ts
src/middleware/node/on-unhandled-request-default.ts

Fixes #230.
I see also two imports 
```typescript
import { createServer } from "http";
```
Not sure if I need to do anything about them or it's just about types.

fix: remove type imports from "http" for Deno compatibility

---

src/middleware/node/index.ts

see https://cdn.skypack.dev/-/@octokit/app@v12.0.1-kdfMCfq9xqcmWHFjAsTl/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts. Part of resolving https://github.com/octokit/octokit.js/issues/24

fix(typescript): avoid `import { App } from "../...d.ts"` in types export

---

README.md
package-lock.json
package.json
src/middleware/node/index.ts
test/node-middleware.test.ts

fixes #236
This is a bit more challenging than hoped. I think in order to make the middleware compatible with `express`, we have to check if either of the two combined middlewares handles the current request and only execute them if they do. Otherwise check for the presence of the 3rd `next` parameter and run it instead of the `onUnhandledRequest` callback function

fix: make node middleware compatible with `express`

---

package-lock.json
package.json

`@octokit/webhooks` dropped compatibility with NodeJS v10 and v12 (octokit/webhooks.js#555), and it was merged into this repo, without creating a new major release.
This reverts commit 635708c827720614bf5fecc95bdafeb1170d38ec.

fix: revert dependency on `@octokit/webhooks` to v9

---

package-lock.json
package.json
test/readme-examples.test.ts

The `POST https://github.com/login/oauth/access_token` endpoint is documented as accepting an optional `state` parameter in the [GitHub App section](https://docs.github.com/en/developers/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps#2-users-are-redirected-back-to-your-site-by-github) but not in the [OAuth App section](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github).
`state` is designed to let front-end code differentiate valid authorizations from forged attacks:
> `state` is a random string to protect against forgery attacks and could contain any other arbitrary data.
> If the user accepts your request, GitHub redirects back to your site with a temporary code in a code …

fix: github api does not need `state` when creating a token

---

src/webhooks.ts

- no previous behavior is changed
- all requests sent using the `octokit` instance passed to an `octokit.webhooks.on(eventName, callback)` callback will now set a `set-x-github-delivery-header` header to the webhook event's delivery GUID.
- I would like to enventually add this as best practice to https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28. We discussed it in the past but it was never a high priority. Setting the header basically allows GitHub Support to trace a request back to the webhook event that triggered it, and what other requests have been sent in response to the same webhook event.
But until it's official, I would consider this an unstable feature. I'd like to add it as I'm working on some webhooks tooling where this would come in …

feat: (unstable) set `x-github-delivery` header on requests sent in response to webhook event

---

.github/workflows/release.yml
scripts/fix-package-json.js

Relates to https://github.com/octokit/plugin-retry.js/pull/410#issuecomment-1506180010
---
- fix(ci): add hotfix in built package.json to use proper file patterns in "files"
- ci(release): run 'scripts/fix-package-json.js' before release
----
The released npm package is missing most of the files generated by the build step. `dist-node`, `dist-types`, `dist-web`... even though they are generated correctly.
You can read more about my explanation in the linked issue.
I expected npm to read the file patterns correctly so we publish all the necessary files again.
This is a mix of an issue with `npm@v9` (https://github.com/npm/cli/issues/6164) and the fact we rely on `pika` for the build step. Pika has been archived [since April 2022](https://github.com/FredKSchott/pika-pack) so there is …

add script to fix package json from build step

---

package-lock.json
package.json

This should help make sure that users of CDNs like esm.sh get the correct working version.
Currently, it is loading version 4.0.10 of `@octokit/auth-app` which is a broken release
See https://github.com/octokit/octokit.js/issues/2459#issuecomment-1565089198 https://github.com/octokit/octokit.js/issues/2450
----
* Users that are utilizing this package via a CDN of the likes of `esm.sh` or skypack, can run into caching issues where they aren't offered the latest release of a dependency.
* Due to that, they might get a broken release of a dependency
* Upgrades the dependency that is causing problems to users
*
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the …

fix(deps): upgrade `@octokit/auth-app`

---

package-lock.json
package.json

Relates to:
* https://github.com/octokit/webhooks.js/pull/914
* https://github.com/octokit/webhooks.js/pull/915
* https://github.com/octokit/webhooks.js/pull/916
* https://github.com/octokit/webhooks.js/pull/917
Fixes an issue where webhooks.js was throwing an error which could cause downstream problems.

fix: update for the handling of an error being thrown by the verify method in webhooks.js

---

package.json
scripts/build.mjs
src/each-installation.ts
src/each-repository.ts
src/get-installation-octokit.ts
src/index.ts
src/middleware/node/index.ts
src/types.ts
src/webhooks.ts
test/each-installation.test.ts
test/each-repository.test.ts
test/get-installation-octokit.test.ts
test/log.test.ts
test/node-middleware.test.ts
test/oauth.test.ts
test/octokit.test.ts
test/readme-examples.test.ts
test/smoke.test.ts
test/tsconfig.test.json
test/typescript-validate.ts
test/webhooks.test.ts

This PR replaces NodeJS internal module imports with `node:` specifier imports, and also updates imports to use full relative paths.

refactor: use `node:` specifier imports and full relative paths

---

README.md
package-lock.json
package.json
scripts/build.mjs
test/log.test.ts
test/node-middleware.test.ts
test/octokit.test.ts
test/tsconfig.test.json

BREAKING CHANGE: package is now ESM

feat: package is now ESM

---

src/index.ts

This resolves issues in consumers of this package getting errors from TypeScript
```
The inferred type of 'App' cannot be named without a reference to '../node_modules/@octokit/app/dist-types/types.js'. This is likely not portable. A type annotation is necessary.
```
----
* 
* 
----

fix(types): export minimal types required for the `App` class

---

README.md
src/get-installation-url.ts
src/index.ts
src/types.ts
test/get-installation-url.test.ts

Resolves #541 
----
* determining the installation url for the github app requires searching the docs and finding both the required installation url _and_ the `GET /app` endpoint for getting the metadata for the current app
* the `app.getInstallationUrl({ state, target_id })` method crafts the installation url for the user
----
Don't love how `getInstallationUrl` looks so similar to `getInstallationOctokit` but "installation" means something different. `octokit/oauth-methods.js` uses `getWebFlowAuthorizationUrl` but `getWebFlowInstallationUrl` seemed a little unnecessarily long
The other caveat is that the base url gets cached, so it won't update if someone …

[FEAT] add `getInstallationUrl` method

---

.github/workflows/test.yml

It is not used currently
----
* There was a command in the `test.yml` workflow file to update NPM that was unused because it was only run on Node 14
* We don't support Node 14 anymore
* Removes the extraneous NPM update that wasn't run
----

ci: remove extraneous command to update `npm`

---

package-lock.json
package.json
test/deprecations.test.ts
test/each-installation.test.ts
test/each-repository.test.ts
test/get-installation-octokit.test.ts
test/get-installation-url.test.ts
test/log.test.ts
test/node-middleware.test.ts
test/oauth.test.ts
test/octokit.test.ts
test/readme-examples.test.ts
test/smoke.test.ts
test/webhooks.test.ts
vite.config.js

Jest is causing issues, and simply put vitest has typescript support out of the box
----
* We were using Jest and it has caused some issues, it doesn't support TypeScript out of the box, or even ESM
* Switch to Vitest as with other repositories, it supports typescript and ESM out of the box
----

build: switch to vitest

---

package.json
src/index.ts

refactor: adapt code for the `exactOptionalPropertyTypes`

---

package-lock.json
package.json

----
* The `verifyWithFallback()` function was missing from the web code in `@octokit/webhooks-methods`, and was only defined for Node, leaving users unable to use newer versions of `@octokit/webhooks` with this package
* Bump `@octokit/webhooks` to pull in a newer version of `@octokit/webhooks-methods`
----

fix(deps): bump `@octokit/webhooks` in order to fix web users

---

package-lock.json
package.json

Bump @octokit/plugin-paginate-rest, @octokit/types, and @octokit/webhooks
----
* Getting `Property 'paginate' is missing in type 'Octokit' but required in type '{ paginate: PaginateInterface; }'` error related to webhook types.
* Bump `@octokit/webhooks` to pull new version of `@octokit/openapi-webhooks-types` that fixes it
* `@octokit/plugin-paginate-rest, @octokit/types` are bumped together
----

fix(deps): bump `@octokit/types` to v13.8.0

---

.github/workflows/test.yml
package.json
scripts/build.mjs

BREAKING CHANGE: Drop support for NodeJS v18

ci: stop testing against NodeJS v18
